version: '3'  # 도커 컴포즈 파일의 버전
services:  # 애플리케이션의 서비스 정의

  rmcalc-express: # 서비스 이름
    image: gillilo/rmcalc-express:latest  # 사용할 도커 이미지
    # build:  # 이미지를 빌드하는 옵션
    #   context: ./rmcalc-express  # Dockerfile이 위치한 경로
    #   dockerfile: Dockerfile  # 사용할 Dockerfile의 이름
    container_name: rmcalc-express  # 컨테이너 이름
    # environment:  # 환경 변수 설정
    #   - VAR_NAME=value
    ports:  # 포트 매핑
      - 81:81
    # volumes:  # 볼륨 마운트
    #   - host_path:container_path
    # networks:  # 네트워크 설정
    #   - rmcalc
    # depends_on:  # 의존하는 서비스
    #   - other_service
    restart: always  # 재시작 정책
    logging:  # 로깅 설정
      driver: json-file  # 로깅 드라이버
      options:
        max-size: "200k"
        max-file: "10"

  rmcalc-web:
    image: gillilo/rmcalc-web:latest
    container_name: rmcalc-web
    # networks:
    #   - rmcalc
    depends_on:
      - rmcalc-express
    environment:  # 환경 변수 설정
      - RMCALC_EXPRESS_URL=http://rmcalc-express:81
    ports:  # 포트 매핑
      - 3000:3000
    restart: always
    logging:  # 로깅 설정
      driver: json-file  # 로깅 드라이버
      options:
        max-size: "200k"
        max-file: "10"

networks:  # 네트워크 정의
  rmcalc:
    driver: bridge  # 네트워크 드라이버

# volumes:  # 볼륨 정의
#   volume_name:
#     driver: local  # 볼륨 드라이버
