version: '3'
services:

  rmcalc-express:
    image: gillilo/rmcalc-express:latest
    container_name: rmcalc-express
    ports:
      - 81:80
    restart: on-failure

  rmcalc-web:
    image: gillilo/rmcalc-web:latest
    container_name: rmcalc-web
    depends_on:
      - rmcalc-express
    environment:
      - RMCALC_EXPRESS_URL=http://rmcalc-express
    ports:
      - 82:3000
    restart: on-failure

networks:
  rmcalc:
    driver: bridge